### ISSUE TITLE
Python 3.x Support

### ISSUE THREAD

**Issue by snookie** [juanriaza/django-rest-framework-msgpack#3]
Theres no Python 3.x support. :(

**Comment by iho** [comment]
Its why I have error on instalation?
+1

**Comment by robertobarreda** [comment]
Resolved in #4 waiting for 1.0.2 release version

**Comment by juanriaza** [comment]
Sorry @snookie @iho @robertobarreda for not being responsive. Will try to release a new version this very weekend.

**Comment by frensjan** [comment]
@juanriaza any chance a new version will be released?

**Comment by kodeine** [comment]
any updates?

**Comment by avanov** [comment]
Is there a chance to see current master branch released on PyPI?

**Comment by juanriaza** [comment]
I've just published a new version with Python 3 compatibility.
